jdk:
  - openjdk8
language: scala

env:
  - SCALAJS_VERSION=0.6.33
  - SCALAJS_VERSION=1.1.1

before_install:
  - nvm install 12
  - curl -o- -L https://yarnpkg.com/install.sh | bash

script: "sbt -Ddocgen.log -Ddocgen.dump +test"

deploy:
  provider: script
  script: "sbt +publish"
  on:
    tags: true
